### ISSUE TITLE
Send normal HTML in article.content.body

### ISSUE THREAD

**Issue by jeena** [arturovm/pond#15]
All other servers send normal not escaped HTML in the JSON, like:

```
{
    "content": "<a href=\"http://example.com\">Example</a>"
}
```

But Pond escapes it before sending:

```
{
    "content": "\u0026lt;a href=\u0026#34;http://example.com/\u0026#34;\u0026gt;Example\u0026lt;/a\u0026gt;"
}
```

Which in my opinion is not necessary and unconventional.

Btw. what is the `text` type and how do you distinguish `xhtml` and `html`?

**Comment by arturovm** [comment]
Right. Was thinking to perhaps only escape HTML tags for the text type, but even that won't be necessary (after all, the type is there so clients know how to display the content).
The Atom spec defines two types: `text` and `xhtml`, while the RSS "spec" (ughhh) doesn't define any so it is assumed to always be HTML. So when you see the `html` type, that's coming from an RSS feed.

The good news here is that XHTML is stricter than HTML, not semantically but syntactically, so you can safely use an HTML parser for both.
