### ISSUE TITLE
Some Atom feeds lose their HTML-Tags

### ISSUE THREAD

**Issue by jeena** [arturovm/pond#19]
Check out this Atom feed: http://caseorganic.com/notes.atom it has HTML in its `<content>` tags like:

```
<content type="xhtml" xml:base="http://caseorganic.com/notes/2014/02/11/1/" xml:space="preserve">
  <div xmlns="http://www.w3.org/1999/xhtml"> 
    <p>Sony sells its waterproof mp3 player inside a bottle of water. 
      <a href="http://thenextweb.com/shareables/2014/02/11/sony-sells-waterproof-mp3-player-inside-bottle-water/">
        thenextweb.com/shareables/2014/02/11/sony-sells-waterproof-mp3-player-inside-bottle-water/
      </a>
    </p> 
  </div>
</content>
```

But after parsing it `bodyNodes[0].Content()` in https://github.com/ArturoVM/pond/blob/master/articles_download.go#L169 returns just the text without the HTML. I'm not sure why this is happening and it doesn't happen to all the atom feeds, but to this one it happens.

**Comment by arturovm** [comment]
I dug around the [gokogiri](https://github.com/moovweb/gokogiri) and libxml2 sources, and it turns out I'm using the wrong API call. `bodyNodes[0].Content()` is appropriate when the node is text–only, but when it has tags inside, I should be calling `bodyNodes[0].InnerHTML()`.

I'll fix that ASAP. I'm working on #8 right now :P

**Comment by jeena** [comment]
No hurry, I just fixed it in my local repo, thanks for looking into it :)

**Comment by arturovm** [comment]
Great! Mind if I ask you for a favor? I think the `String()` function might be even better, because it just dumps the node's content into a byte buffer and then casts it into a regular string, so it might work for both cases. Could you please test it out?

**Comment by jeena** [comment]
It is almost there, it gives you the &lt;content> tag too which you normally don't want to have.

**Comment by arturovm** [comment]
So the only choice is to test the content type? Damn... this will be tricky with RSS, since it doesn't formally define types, and feed items may or may not have tags in them, arbitrarily.

**Comment by jeena** [comment]
Why not just use InnerHtml() everywhere? That way you will get just text if it is only text and if it is HTML then you get the normal tags too?

**Comment by arturovm** [comment]
Done. Also added HTML unescaping because I discovered some RSS feeds escape their HTML (such as [Marco Arment's](http://marco.org))
