### ISSUE TITLE
How to reset everything?

### ISSUE THREAD

**Issue by jeena** [arturovm/pond#21]
Sometimes I just want to reset the database. I tried to just remove the db.db file so it would create a new one and it does. But then when I go to /api/setup it says I have insufficient privileges to create a admin user. This does not happen if I clone the project to some other directory.

Btw. I have to delete the user cookie manually because if the db changes I can not log out anymore.

**Comment by arturovm** [comment]
You also have to delete `prefs.gob`.

Yeah, that's a bug. Thanks. The client should delete the cookie if the server returns `401` with its current token.

**Comment by jeena** [comment]
Ah prefs.gob, I hear you, thanks!
