### ISSUE TITLE
Name conflict?

### ISSUE THREAD

**Issue by arnehormann** [arturovm/pond#5]
I stumbled over (your) Pond in the Go Advent article, but a project by that name already exists.
https://pond.imperialviolet.org/
It's written by [Adam Langley](https://github.com/agl/pond), main author of the Go TLS implementation.
Normally not a problem, but both projects are communication and crypto focussed and written in Go.

**Comment by arturovm** [comment]
Hi arnehorman. Yeah, that is an unfortunate collision :/ I will paste what I said in the article's comments:

Yup. I asked Adam Langley about it and he said it's ok. Besides, they're two totally unrelated protocols in two totally unrelated fields.
That said, a name change is something I'm seriously considering.

**Comment by arnehormann** [comment]
I'm sorry this is a duplicate. I didn't read the comments.

**Comment by arturovm** [comment]
No problem!

My fault too. This should be more visible. Perhaps I'll add it to the README.

(Sorry for the delayed response, btw. Been out on holiday.)

–A.

**Comment by jeena** [comment]
In my opinion the name is ok for the example implementation but you really should change the name of the protocol to something else, more official like "Feed Status Syndication Protocol"  FSSP or something.

I think it is really problematic that the protocol and the example implementation have the same name, this was not a good idea for Tent and it is not for Pond either.
