### ISSUE TITLE
Protocol is vulnerable to replay attacks

### ISSUE THREAD

**Issue by markberger** [arturovm/pond#6]
I don't know a lot about crypto,, but based on what I've read in the api doc, it seems to me that pond is vulnerable to [replay attacks](http://en.wikipedia.org/wiki/Replay_attack). Anyone who intercepts a user's MD5 hash will be able to login as that user. The protocol should be amended to implement a mechanism which prevents such an attack.

**Comment by arturovm** [comment]
Yes indeed. Thank you :) I hadn't had much time to reply to this, but I've been working on a security draft for the protocol. You can find it [here](https://arturovm.me/post/pond-threat-model-draft-1.html). I'll add it to the README in the master branch.

Let me know what you think.
