### ISSUE TITLE
Add --verbose mode

### ISSUE THREAD

**Issue by jeena** [arturovm/pond#8]
It would be cool if one could use a --verbose mode to see what requests are coming in into pond for development.

**Comment by arturovm** [comment]
Added verbose mode. Usage details are in the README at branch `develop`.

Could you do me a favor? Checkout `develop` and try to build it, please.

**Comment by jeena** [comment]
Very nice! But could you print out even stuff which leads to a 404 or any other error?

**Comment by jeena** [comment]
You could also have a look at what rails does, which does it quite nice because they log a dictionary with the stuff which really got into the program, not only what the browser/client send. That way you can see if you've done it right if rails was able to parse your stuff right or not.

In my case when I send the wrong Content-Type this verbose mode wouldn't help me much because I can see `username=jeena&password=abcdef33fa213f41d41694c4d2f3f4` but I still get `{"error": "Not enough parameters to log in"}` which is not very helpfull because you think: "What? Not enough? There are only two parameters mentioned in the documentation, username and password, how can this be not enough?"

**Comment by arturovm** [comment]
Verbose logging now works as requested :)
